### ISSUE TITLE
Internet Gateway failing to attach

### ISSUE THREAD

**Issue by rubenhak** [berlioz-the/berlioz#1]
Internet Gateway is failing to attach. Two issues here:
1. If IG is already attached to VPC no need to attach again.
2. Gracefully handle already attached error.

```
2018-06-02T17:47:38.473Z> AWSus-east-1 | INFO | Attaching InternetGateway igw-e748039f to vpc-3c7d7347...
2018-06-02T17:47:38.475Z> Throttlerec2 | INFO | Executing attachInternetGateway...
2018-06-02T17:47:38.505Z> Throttlerec2 | WARN | Failed attachInternetGateway.
2018-06-02T17:47:38.505Z> AWSus-east-1 | WARN | IG igw-e748039f is already attached. Original reason: { Resource.AlreadyAssociated: resource igw-e748039f is already attached to network vpc-3c7d7347
    at Request.extractError (/var/task/core/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/var/task/core/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/core/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/core/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/core/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/core/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/core/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/core/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/core/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/task/core/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'resource igw-e748039f is already attached to network vpc-3c7d7347',
  code: 'Resource.AlreadyAssociated',
  time: 2018-06-02T17:47:38.505Z,
  requestId: '905b92aa-78a9-4af5-bb27-4256439ca795',
  statusCode: 400,
  retryable: false,
  retryDelay: 7.493464704265418 }

```

**Comment by rubenhak** [comment]
Fixed in recent robot version.
