### ISSUE TITLE
Error running 'berlioz local push-run'

### ISSUE THREAD

**Issue by rubenhak** [berlioz-the/berlioz#2]
Intermittently receive this error when building images. 

```
ERROR: LocalDeployer/19908 on HomePC:
    Reason:  { Error: (HTTP code 404) no such image - no such image: berliozcloud/agent: No such image: berliozcloud/agent:latest
        at C:\Users\Ruben\AppData\Roaming\npm\node_modules\berlioz\node_modules\docker-modem\lib\modem.js:254:17
        at getCause (C:\Users\Ruben\AppData\Roaming\npm\node_modules\berlioz\node_modules\docker-modem\lib\modem.js:284:7)
        at Modem.buildPayload (C:\Users\Ruben\AppData\Roaming\npm\node_modules\berlioz\node_modules\docker-modem\lib\modem.js:253:5)
        at IncomingMessage.<anonymous> (C:\Users\Ruben\AppData\Roaming\npm\node_modules\berlioz\node_modules\docker-modem\lib\modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1056:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
      reason: 'no such image',
      statusCode: 404,
      json:
       { message: 'no such image: berliozcloud/agent: No such image: berliozcloud/agent:latest' } }
ERROR: Failed to deploy cluster hello
ERROR: Reason: {
  "reason": "no such image",
  "statusCode": 404,
  "json": {
    "message": "no such image: berliozcloud/agent: No such image: berliozcloud/agent:latest"
  }
}
```

Workaround: manually run **docker pull berliozcloud/agent:latest**

**Comment by berlioz-the** [comment]
Fixed in v.1.2.
